services:
  # Service 1: The Database
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Persist data even if container stops

  # Service 2: The FastAPI Backend
  backend:
    build: ./server
    container_name: backend_container
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
    # We mount the volume so code changes reflect immediately (Hot Reloading)
    volumes:
      - ./server:/app

  frontend:
    build: ./client
    container_name: frontend_container
    restart: always
    ports:
      - "5173:5173"
    environment:
      # This points to the Backend from the browser's perspective
      - VITE_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./client:/app
      # ONE OF THE MOST IMPORTANT LINES IN DOCKER:
      # This prevents your local empty node_modules from overriding the
      # container's installed node_modules.
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo_data:
